### ISSUE TITLE
Can submit record without exam information

### ISSUE THREAD

**Issue by panaschristou** [gcivil-nyu-org/INT2-Monday-Spring2024-Team-1#211]
You can submit a record without filling in any of the information that corresponds to each exam. I am not sure if that is intended because maybe the patient can fill it in later but I thought I would create an issue for it.

**Comment by shreyas2499** [comment]
@panaschristou, thanks for pointing this out. And you are right, the patient can submit the form without entering those details. The main reason for keeping the fields as optional is because the patient might not have the necessary details. Details such as the hemoglobin count, platelet count, cylindrical powers, etc might not always be available to the patient while filling out the form. In such cases, the hospital admin can also then fill out the form on behalf of the patient. 
Do let me know if you have any further questions!
